baseURL = 'https://revrost.com/'
languageCode = 'en-us'
title = 'reVrost'
theme = 'papermod'
Copyright = '© 2017-2023 revrost.com'

[params]
author = "Kenley Bastari"
defaultTheme = "light" # dark, light
ShowShareButtons = false
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
# ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
# ShowToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false

[params.homeInfoParams]
Title = "About"
ImageURL = "https://avatars.githubusercontent.com/u/1558599?v=4"
Content = """
Hi there, I'm Kenley [(@revrost)](https://github.com/revrost), an engineer currently working at Immutable. I've been building software since I was 11 years old. Building products that people *use* is my biggest passion.

<br>

I am all for action over inaction and value iterating over planning. You can probably find me talking about cloud architecture, software philosophy, stock investing, fight club culture, and a sprinkle of LLMs.

<br><br>

On the side, I'm currently working on [Marketpal](https://marketpal.ai). Thanks for stopping by!
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/revrost"

[[params.socialIcons]]
name = "kofi"
url = "https://ko-fi.com/revrost"

[[languages.en.menu.main]]
name = "Posts"
url = "posts"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10
